src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, groups={"insertion"}, message="Email looks like already exist!")
 * @UniqueEntity(fields={"username"}, groups={"insertion"}, message="Username looks like already exist!")
 */
class User implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=100, unique=true)
     *
     * @Assert\NotBlank(message = "Username should not be blank", groups={"insertion"})
     * @Assert\Length(
     *      min = 5,
     *      max = 100,
     *      minMessage = "Username must be at least {{ limit }} characters long",
     *      maxMessage = "Username cannot be longer than {{ limit }} characters",
     *      groups={"insertion"}
     * )
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     *
     * @Assert\NotBlank(message = "Password should not be blank", groups={"insertion"})
     * @Assert\Length(
     *      min = 5,
     *      max = 20,
     *      minMessage = "Password must be at least {{ limit }} characters long",
     *      maxMessage = "Password cannot be longer than {{ limit }} characters",
     *      groups={"insertion"}
     * )
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=100)
     *
     * @Assert\NotBlank(message = "Firstname should not be blank", groups={"insertion"})
     * @Assert\Length(
     *      min = 1,
     *      max = 100,
     *      minMessage = "Username must be at least {{ limit }} characters long",
     *      maxMessage = "Username cannot be longer than {{ limit }} characters",
     *      groups={"insertion"}
     * )
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="surname", type="string", length=100, nullable=true)
     */
    private $surname;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100, unique=true, nullable=false)
     *
     * @Assert\NotBlank(message = "Email should not be blank", groups={"insertion"})
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     *     checkMX = true,
     *     groups = {"insertion"}
     * )
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="thumb", type="string", length=100, nullable=true)
     */
    private $thumb;

    /**
     * @var \AppBundle\Entity\UserGroup
     * @ORM\ManyToOne(targetEntity="UserGroup")
     * @ORM\JoinColumn(name="role", referencedColumnName="id")
     */
    private $role;

    /**
     * @var bool
     *
     * @ORM\Column(name="deleted", type="boolean", options={"default" : 0})
     */
    private $deleted = 0;



    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        dump($this->getRole()->getGroupKey());
        return [ $this->getRole()->getGroupKey() ];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        return null;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set surname
     *
     * @param string $surname
     *
     * @return User
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * Get surname
     *
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set thumb
     *
     * @param string $thumb
     *
     * @return User
     */
    public function setThumb($thumb)
    {
        $this->thumb = $thumb;

        return $this;
    }

    /**
     * Get thumb
     *
     * @return string
     */
    public function getThumb()
    {
        return $this->thumb;
    }

    /**
     * Set deleted
     *
     * @param boolean $deleted
     *
     * @return User
     */
    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * Get deleted
     *
     * @return boolean
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /////////////////////////// Some Func ////////////////////////
    /**
     * Get full name
     *
     * @return string
     */
    public function getFullname()
    {
        return $this->firstname . " " . $this->surname;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return "bundles/AppBundle/images/user/" . (empty($this->thumb)?"user.png":$this->thumb);
    }

    /**
     * Set role
     *
     * @param \AppBundle\Entity\UserGroup $role
     *
     * @return User
     */
    public function setRole(\AppBundle\Entity\UserGroup $role = null)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return \AppBundle\Entity\UserGroup
     */
    public function getRole()
    {
        return $this->role;
    }
}

src/AppBundle/Resources/views/error.html.twig
{% if errors is defined and errors is not empty %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                {% for error in errors %}
                    <strong>{{ error.message }}</strong><br/>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

src/AppBundle/Resources/views/foot.html.twig
<!-- jQuery -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- FastClick -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/fastclick/lib/fastclick.js') }}"></script>
<!-- NProgress -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/nprogress/nprogress.js') }}"></script>
<!-- gauge.js -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/gauge.js/dist/gauge.min.js') }}"></script>
<!-- bootstrap-progressbar -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
<!-- iCheck -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/iCheck/icheck.min.js') }}"></script>
<!-- JQVMap -->
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
<!-- Custom Theme Scripts -->
{{ scripts|raw }}
<script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/build/js/custom.min.js') }}"></script>

src/AppBundle/Resources/views/head.html.twig
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Admin panel</title>

<!-- Bootstrap -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/vendors/bootstrap/dist/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/vendors/font-awesome/css/font-awesome.min.css') }}">
<!-- NProgress -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/vendors/nprogress/nprogress.css') }}">
<!-- iCheck -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/vendors/bootstrap/dist/css/bootstrap.min.css') }}">

<!-- bootstrap-progressbar -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/vendors/jqvmap/dist/jqvmap.min.css') }}">
<!-- Custom Theme Style -->
<link rel="stylesheet" type="text/css" href="{{ asset('css/assets/build/css/custom.min.css') }}">

{{ css|raw }}

src/AppBundle/Resources/views/home.html.twig
{% extends "AppBundle::master.html.twig" %}

{% block content %}

{% endblock %}

src/AppBundle/Resources/views/master.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'AppBundle::head.html.twig' with { css: block('css') } %}
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        {% include 'AppBundle::menu.html.twig' %}

        <!-- page content -->
        <div class="right_col" role="main">
            {% block content %}

            {% endblock %}
        </div>
        <!-- /page content -->

        <footer>
            <div class="pull-right">
                Created by <a href="">A.Terlan</a>
            </div>
            <div class="clearfix"></div>
        </footer>
    </div>
</div>

{% include 'AppBundle::foot.html.twig' with { scripts: block('scripts') } %}

</body>
</html>

src/AppBundle/Resources/views/menu.html.twig
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{ path('admin_home') }}" class="site_title"><i class="fa fa-paw"></i> <span>Admin Panel</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{ asset(app.user.photo) }}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ app.user.fullname }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a href="{{ path('admin_home') }}"><i class="fa fa-home"></i> Home </a></li>
                    <li><a href="{{ path('admin_users') }}"><i class="fa fa-user"></i> Users </a></li>
                    <li><a href="{{ path('admin_groups') }}"><i class="fa fa-group"></i> Groups </a></li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ path('admin_logout') }}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{ asset(app.user.photo) }}" alt="">{{ app.user.fullname }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ path('admin_profile') }}"> Profile</a></li>
                        <li><a href="{{ path('admin_logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green"></span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">

                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

src/AppBundle/Resources/views/pagination.html.twig
{# default Sliding pagination control implementation #}

{% if pageCount > 1 %}
    <div class="btn-group">
        {% if first is defined and current != first %}
                <a class="btn btn-info" href="{{ path(route, query|merge({(pageParameterName): first})) }}">&lt;&lt;</a>
        {% endif %}

        {% if previous is defined %}
            <a class="btn btn-info" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&lt;</a>
        {% endif %}

        {% for page in pagesInRange %}
            {% if page != current %}
                <a class="btn btn-info" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
            {% else %}
                <a class="btn btn-info active">{{ page }}</a>
            {% endif %}

        {% endfor %}

        {% if next is defined %}
            <a class="btn btn-info" href="{{ path(route, query|merge({(pageParameterName): next})) }}">&gt;</a>
        {% endif %}

        {% if last is defined and current != last %}
            <a class="btn btn-info" href="{{ path(route, query|merge({(pageParameterName): last})) }}">&gt;&gt;</a>
        {% endif %}
    </div>
{% endif %}

src/AppBundle/Resources/views/profile.html.twig
{% extends "AppBundle::master.html.twig" %}

{% block content %}
    {% include 'AppBundle::error.html.twig' %}

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Profile</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    {{ form_start(formInfo) }}
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ form_label(formInfo.image) }}</label>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="thumbnail" style="height: 150px;width: 150px;">
                                    <div class="image view view-first" style="height: 100%;">
                                        <img style="width: 140px;height: 140px;display: block;" src="{{ asset(app.user.photo) }}" alt="profil photo">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3" style="padding-top: 130px;">
                                {{ form_widget(formInfo.image) }}
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ form_label(formInfo.name) }}
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ form_widget(formInfo.name) }}
                                <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ form_label(formInfo.surname) }}
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ form_widget(formInfo.surname) }}
                                <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">{{ form_label(formInfo.login) }}
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ form_widget(formInfo.login) }}
                            </div>
                        </div>
                        <div class="item form-group">
                            <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">{{ form_label(formInfo.email) }}</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ form_widget(formInfo.email) }}
                                <span class="fa fa-envelope form-control-feedback left" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                {{ form_widget(formInfo.save) }}
                            </div>
                        </div>
                    {{ form_end(formInfo) }}
                </div>
            </div>
        </div>
    </div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Password</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br>
                {{ form_start(formPass) }}
                    <div class="item form-group">
                        <label for="old_password" class="control-label col-md-3">{{ form_label(formPass.old_password) }} <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ form_widget(formPass.old_password) }}
                        </div>
                    </div>
                    <div class="item form-group">
                        <label for="password" class="control-label col-md-3">{{ form_label(formPass.password) }} <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ form_widget(formPass.password) }}
                        </div>
                    </div>
                    <div class="item form-group">
                        <label for="re_password2" class="control-label col-md-3 col-sm-3 col-xs-12">{{ form_label(formPass.re_password) }} <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ form_widget(formPass.re_password) }}
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            {{ form_widget(formPass.save) }}
                        </div>
                    </div>
                {{ form_end(formPass) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ asset('bundles/AppBundle/assets/vendors/validator/validator.js') }}"></script>
{% endblock %}